### ISSUE TITLE
No dataset (sparse_50318_for_26types.npz) from website

### ISSUE THREAD

**Issue by ShuilinLiao** [AsaHIXx/CTCT#2]
Hello, I want to reproduce training process, but there is no dataset (sparse_50318_for_26types.npz) from the website(http://117.25.169.110:1032/). Can you check for this?

**Comment by AsaHIXx** [comment]
Hello Shuilin, simply click the `search` button, and the file will be displayed. :)

**Comment by ShuilinLiao** [comment]
Thank you for your reply. I have downloaded the data succeessfully.
